POST https://fast-cove-37716.herokuapp.com/api/persons/
Content-Type: application/json

{
  "name": "Mariano Andres",
  "number": "5555-1234"
}


###
DELETE https://fast-cove-37716.herokuapp.com/api/persons/5

